version: '3'
services:
  nodered:
    build: .
    ports:
     - "1880:1880"
     - "1881:1881/udp"
    volumes:
     - nodered-data:/data
    networks:
      - nodered-net
volumes:
  nodered-data:
networks:
  nodered-net:
